/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Account {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "username")]
    pub username: String,
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
    #[serde(rename = "provider")]
    pub provider: Provider,
    /// Provider-specific metadata.
    #[serde(rename = "data")]
    pub data: serde_json::Value,
    #[serde(rename = "authorized")]
    pub authorized: bool,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl Account {
    pub fn new(id: i32, uuid: uuid::Uuid, name: String, username: String, provider: Provider, data: serde_json::Value, authorized: bool, created_at: String) -> Account {
        Account {
            id,
            uuid,
            name,
            username,
            image: None,
            provider,
            data,
            authorized,
            created_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Provider {
    #[serde(rename = "instagram")]
    Instagram,
    #[serde(rename = "tiktok")]
    Tiktok,
    #[serde(rename = "pinterest")]
    Pinterest,
    #[serde(rename = "twitter")]
    Twitter,
    #[serde(rename = "linkedin")]
    Linkedin,
    #[serde(rename = "facebook_page")]
    FacebookPage,
    #[serde(rename = "youtube")]
    Youtube,
    #[serde(rename = "mastodon")]
    Mastodon,
}

impl Default for Provider {
    fn default() -> Provider {
        Self::Instagram
    }
}

