/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddGenericSubscriptionRequest {
    #[serde(rename = "plan_id")]
    pub plan_id: i32,
    #[serde(rename = "trial_days", skip_serializing_if = "Option::is_none")]
    pub trial_days: Option<i32>,
    #[serde(rename = "keep_prev_trial_ends_at")]
    pub keep_prev_trial_ends_at: bool,
}

impl AddGenericSubscriptionRequest {
    pub fn new(plan_id: i32, keep_prev_trial_ends_at: bool) -> AddGenericSubscriptionRequest {
        AddGenericSubscriptionRequest {
            plan_id,
            trial_days: None,
            keep_prev_trial_ends_at,
        }
    }
}

