/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlogToSocialCaption {
    /// ID of the social account this caption was generated for.
    #[serde(rename = "account_id", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<i32>,
    /// Social media platform identifier.
    #[serde(rename = "provider", skip_serializing_if = "Option::is_none")]
    pub provider: Option<String>,
    /// The generated caption text. `null` if generation failed for this account.
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Character count of the generated content. `null` if generation failed.
    #[serde(rename = "character_count", skip_serializing_if = "Option::is_none")]
    pub character_count: Option<i32>,
    /// Maximum allowed character count for this platform.
    #[serde(rename = "character_limit", skip_serializing_if = "Option::is_none")]
    pub character_limit: Option<i32>,
    /// Error message if caption generation failed for this account. `null` on success.
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl BlogToSocialCaption {
    pub fn new() -> BlogToSocialCaption {
        BlogToSocialCaption {
            account_id: None,
            provider: None,
            content: None,
            character_count: None,
            character_limit: None,
            error: None,
        }
    }
}

