/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlogToSocialResponse {
    /// The blog post title (scraped or provided directly).
    #[serde(rename = "blog_title", skip_serializing_if = "Option::is_none")]
    pub blog_title: Option<String>,
    /// A short excerpt from the blog post content.
    #[serde(rename = "blog_excerpt", skip_serializing_if = "Option::is_none")]
    pub blog_excerpt: Option<String>,
    /// Generated captions, one per target account.
    #[serde(rename = "captions", skip_serializing_if = "Option::is_none")]
    pub captions: Option<Vec<models::BlogToSocialCaption>>,
    /// UUID of the created draft post. Only present when `create_post` was `true`.
    #[serde(rename = "post_uuid", skip_serializing_if = "Option::is_none")]
    pub post_uuid: Option<uuid::Uuid>,
    #[serde(rename = "media", skip_serializing_if = "Option::is_none")]
    pub media: Option<Box<models::BlogToSocialMedia>>,
    /// Number of AI credits consumed by this request (one per successful caption).
    #[serde(rename = "credits_used", skip_serializing_if = "Option::is_none")]
    pub credits_used: Option<i32>,
    /// Remaining AI credits for the current billing period. `null` for unlimited plans.
    #[serde(rename = "credits_remaining", skip_serializing_if = "Option::is_none")]
    pub credits_remaining: Option<i32>,
}

impl BlogToSocialResponse {
    pub fn new() -> BlogToSocialResponse {
        BlogToSocialResponse {
            blog_title: None,
            blog_excerpt: None,
            captions: None,
            post_uuid: None,
            media: None,
            credits_used: None,
            credits_remaining: None,
        }
    }
}

