/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BlogToSocialInput : At least one of `url` or (`title` + `excerpt`) must be provided. If both are given, direct values take priority over the scraped URL content. 
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BlogToSocialInput {
    /// Blog post URL to scrape. Required if `title` and `excerpt` are not provided.
    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,
    /// Blog post title. Required if `url` is not provided.
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    /// Blog post summary or excerpt. Required if `url` is not provided.
    #[serde(rename = "excerpt", skip_serializing_if = "Option::is_none")]
    pub excerpt: Option<String>,
    /// Featured image URL for the blog post. When `create_post` is `true`, the image is imported into the workspace media library and attached to the draft post. If omitted in URL mode, the scraper attempts to extract the `og:image` meta tag. 
    #[serde(rename = "image_url", skip_serializing_if = "Option::is_none")]
    pub image_url: Option<String>,
    /// Target social media platforms. Only connected accounts matching these platforms are used. If omitted, all connected accounts in the workspace are targeted. 
    #[serde(rename = "platforms", skip_serializing_if = "Option::is_none")]
    pub platforms: Option<Vec<Platforms>>,
    /// Specific account IDs to generate captions for. Takes precedence over `platforms` when both are provided. 
    #[serde(rename = "account_ids", skip_serializing_if = "Option::is_none")]
    pub account_ids: Option<Vec<i32>>,
    /// Writing tone for all generated captions.
    #[serde(rename = "tone", skip_serializing_if = "Option::is_none")]
    pub tone: Option<Tone>,
    /// Desired length of the generated captions.
    #[serde(rename = "content_length", skip_serializing_if = "Option::is_none")]
    pub content_length: Option<ContentLength>,
    /// Hashtag quantity: none (0), few (1-3), some (3-5), many (5+).
    #[serde(rename = "hashtags", skip_serializing_if = "Option::is_none")]
    pub hashtags: Option<Hashtags>,
    /// Call-to-action type appended to each caption.
    #[serde(rename = "cta", skip_serializing_if = "Option::is_none")]
    pub cta: Option<Cta>,
    /// Output language as an ISO 639-1 code (e.g. `en`, `de`, `fr`). Use `auto` to match the blog post's language automatically. 
    #[serde(rename = "language", skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    /// Additional instructions appended to the AI prompt (e.g. \"always mention our free tier\").
    #[serde(rename = "custom_instructions", skip_serializing_if = "Option::is_none")]
    pub custom_instructions: Option<String>,
    /// When `true`, creates a draft post in the workspace with per-account caption versions. If an image is available, it is imported and attached to the post. 
    #[serde(rename = "create_post", skip_serializing_if = "Option::is_none")]
    pub create_post: Option<bool>,
}

impl BlogToSocialInput {
    /// At least one of `url` or (`title` + `excerpt`) must be provided. If both are given, direct values take priority over the scraped URL content. 
    pub fn new() -> BlogToSocialInput {
        BlogToSocialInput {
            url: None,
            title: None,
            excerpt: None,
            image_url: None,
            platforms: None,
            account_ids: None,
            tone: None,
            content_length: None,
            hashtags: None,
            cta: None,
            language: None,
            custom_instructions: None,
            create_post: None,
        }
    }
}
/// Target social media platforms. Only connected accounts matching these platforms are used. If omitted, all connected accounts in the workspace are targeted. 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Platforms {
    #[serde(rename = "facebook")]
    Facebook,
    #[serde(rename = "instagram")]
    Instagram,
    #[serde(rename = "x")]
    X,
    #[serde(rename = "linkedin")]
    Linkedin,
    #[serde(rename = "pinterest")]
    Pinterest,
    #[serde(rename = "youtube")]
    Youtube,
    #[serde(rename = "tiktok")]
    Tiktok,
    #[serde(rename = "mastodon")]
    Mastodon,
    #[serde(rename = "threads")]
    Threads,
    #[serde(rename = "bluesky")]
    Bluesky,
    #[serde(rename = "google_business")]
    GoogleBusiness,
}

impl Default for Platforms {
    fn default() -> Platforms {
        Self::Facebook
    }
}
/// Writing tone for all generated captions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Tone {
    #[serde(rename = "neutral")]
    Neutral,
    #[serde(rename = "friendly")]
    Friendly,
    #[serde(rename = "formal")]
    Formal,
    #[serde(rename = "edgy")]
    Edgy,
    #[serde(rename = "engaging")]
    Engaging,
    #[serde(rename = "casual")]
    Casual,
    #[serde(rename = "professional")]
    Professional,
    #[serde(rename = "humorous")]
    Humorous,
    #[serde(rename = "inspirational")]
    Inspirational,
    #[serde(rename = "conversational")]
    Conversational,
}

impl Default for Tone {
    fn default() -> Tone {
        Self::Neutral
    }
}
/// Desired length of the generated captions.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ContentLength {
    #[serde(rename = "short")]
    Short,
    #[serde(rename = "medium")]
    Medium,
    #[serde(rename = "long")]
    Long,
}

impl Default for ContentLength {
    fn default() -> ContentLength {
        Self::Short
    }
}
/// Hashtag quantity: none (0), few (1-3), some (3-5), many (5+).
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Hashtags {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "few")]
    Few,
    #[serde(rename = "some")]
    Some,
    #[serde(rename = "many")]
    Many,
}

impl Default for Hashtags {
    fn default() -> Hashtags {
        Self::None
    }
}
/// Call-to-action type appended to each caption.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Cta {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "question")]
    Question,
    #[serde(rename = "link")]
    Link,
    #[serde(rename = "subscribe")]
    Subscribe,
    #[serde(rename = "follow")]
    Follow,
    #[serde(rename = "share")]
    Share,
    #[serde(rename = "learn_more")]
    LearnMore,
    #[serde(rename = "signup")]
    Signup,
    #[serde(rename = "buy")]
    Buy,
    #[serde(rename = "download")]
    Download,
}

impl Default for Cta {
    fn default() -> Cta {
        Self::None
    }
}

