/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ChangeSubscriptionPlanRequest {
    #[serde(rename = "plan_id")]
    pub plan_id: i32,
    #[serde(rename = "cycle")]
    pub cycle: Cycle,
    #[serde(rename = "prorate")]
    pub prorate: bool,
    #[serde(rename = "billing_immediately")]
    pub billing_immediately: bool,
}

impl ChangeSubscriptionPlanRequest {
    pub fn new(plan_id: i32, cycle: Cycle, prorate: bool, billing_immediately: bool) -> ChangeSubscriptionPlanRequest {
        ChangeSubscriptionPlanRequest {
            plan_id,
            cycle,
            prorate,
            billing_immediately,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Cycle {
    #[serde(rename = "monthly")]
    Monthly,
    #[serde(rename = "yearly")]
    Yearly,
}

impl Default for Cycle {
    fn default() -> Cycle {
        Self::Monthly
    }
}

