/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeletePostsBulkRequest {
    /// Array of post UUIDs to delete.
    #[serde(rename = "posts")]
    pub posts: Vec<uuid::Uuid>,
    /// Move to trash instead of permanent delete.
    #[serde(rename = "trash", skip_serializing_if = "Option::is_none")]
    pub trash: Option<bool>,
    #[serde(rename = "delete_mode", skip_serializing_if = "Option::is_none")]
    pub delete_mode: Option<models::DeleteMode>,
}

impl DeletePostsBulkRequest {
    pub fn new(posts: Vec<uuid::Uuid>) -> DeletePostsBulkRequest {
        DeletePostsBulkRequest {
            posts,
            trash: None,
            delete_mode: None,
        }
    }
}

