/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteMode : - `app_only` — delete from PostBoost only - `app_and_social` — delete from PostBoost and the social platform - `social_only` — delete from the social platform only 
/// - `app_only` — delete from PostBoost only - `app_and_social` — delete from PostBoost and the social platform - `social_only` — delete from the social platform only 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DeleteMode {
    #[serde(rename = "app_only")]
    AppOnly,
    #[serde(rename = "app_and_social")]
    AppAndSocial,
    #[serde(rename = "social_only")]
    SocialOnly,

}

impl std::fmt::Display for DeleteMode {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AppOnly => write!(f, "app_only"),
            Self::AppAndSocial => write!(f, "app_and_social"),
            Self::SocialOnly => write!(f, "social_only"),
        }
    }
}

impl Default for DeleteMode {
    fn default() -> DeleteMode {
        Self::AppOnly
    }
}

