/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageVariationsResponse {
    #[serde(rename = "images")]
    pub images: Vec<models::GeneratedImageItem>,
    #[serde(rename = "aspect_ratio")]
    pub aspect_ratio: String,
    #[serde(rename = "quality")]
    pub quality: String,
    #[serde(rename = "credits_used")]
    pub credits_used: i32,
    #[serde(rename = "credits_remaining", skip_serializing_if = "Option::is_none")]
    pub credits_remaining: Option<i32>,
}

impl ImageVariationsResponse {
    pub fn new(images: Vec<models::GeneratedImageItem>, aspect_ratio: String, quality: String, credits_used: i32) -> ImageVariationsResponse {
        ImageVariationsResponse {
            images,
            aspect_ratio,
            quality,
            credits_used,
            credits_remaining: None,
        }
    }
}

