/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImageVariationsInput {
    #[serde(rename = "media_uuid")]
    pub media_uuid: uuid::Uuid,
    #[serde(rename = "aspect_ratio", skip_serializing_if = "Option::is_none")]
    pub aspect_ratio: Option<AspectRatio>,
    #[serde(rename = "count", skip_serializing_if = "Option::is_none")]
    pub count: Option<i32>,
    #[serde(rename = "quality", skip_serializing_if = "Option::is_none")]
    pub quality: Option<Quality>,
}

impl ImageVariationsInput {
    pub fn new(media_uuid: uuid::Uuid) -> ImageVariationsInput {
        ImageVariationsInput {
            media_uuid,
            aspect_ratio: None,
            count: None,
            quality: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AspectRatio {
    #[serde(rename = "1:1")]
    Variant1Colon1,
    #[serde(rename = "16:9")]
    Variant16Colon9,
    #[serde(rename = "9:16")]
    Variant9Colon16,
    #[serde(rename = "4:5")]
    Variant4Colon5,
}

impl Default for AspectRatio {
    fn default() -> AspectRatio {
        Self::Variant1Colon1
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Quality {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "hd")]
    Hd,
}

impl Default for Quality {
    fn default() -> Quality {
        Self::Standard
    }
}

