/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ImagePromptInput {
    #[serde(rename = "caption")]
    pub caption: String,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<Template>,
    #[serde(rename = "style", skip_serializing_if = "Option::is_none")]
    pub style: Option<String>,
    #[serde(rename = "brand_voice", skip_serializing_if = "Option::is_none")]
    pub brand_voice: Option<String>,
    #[serde(rename = "custom_instructions", skip_serializing_if = "Option::is_none")]
    pub custom_instructions: Option<String>,
}

impl ImagePromptInput {
    pub fn new(caption: String, platform: String) -> ImagePromptInput {
        ImagePromptInput {
            caption,
            platform,
            template: None,
            style: None,
            brand_voice: None,
            custom_instructions: None,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Template {
    #[serde(rename = "blog_cover")]
    BlogCover,
    #[serde(rename = "quote_card")]
    QuoteCard,
    #[serde(rename = "stat_card")]
    StatCard,
    #[serde(rename = "feature_announcement")]
    FeatureAnnouncement,
    #[serde(rename = "product_highlight")]
    ProductHighlight,
    #[serde(rename = "event_promo")]
    EventPromo,
    #[serde(rename = "carousel_slide")]
    CarouselSlide,
    #[serde(rename = "ad_creative")]
    AdCreative,
}

impl Default for Template {
    fn default() -> Template {
        Self::BlogCover
    }
}

