/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InitiateChunkedUpload200Response {
    #[serde(rename = "upload_uuid", skip_serializing_if = "Option::is_none")]
    pub upload_uuid: Option<uuid::Uuid>,
    #[serde(rename = "chunk_size", skip_serializing_if = "Option::is_none")]
    pub chunk_size: Option<i32>,
    #[serde(rename = "total_chunks", skip_serializing_if = "Option::is_none")]
    pub total_chunks: Option<i32>,
}

impl InitiateChunkedUpload200Response {
    pub fn new() -> InitiateChunkedUpload200Response {
        InitiateChunkedUpload200Response {
            upload_uuid: None,
            chunk_size: None,
            total_chunks: None,
        }
    }
}

