/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InitiateRemoteUpload201ResponseOneOf {
    #[serde(rename = "download_id", skip_serializing_if = "Option::is_none")]
    pub download_id: Option<String>,
}

impl InitiateRemoteUpload201ResponseOneOf {
    pub fn new() -> InitiateRemoteUpload201ResponseOneOf {
        InitiateRemoteUpload201ResponseOneOf {
            download_id: None,
        }
    }
}

