/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Media {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "mime_type")]
    pub mime_type: String,
    #[serde(rename = "type")]
    pub r#type: Type,
    #[serde(rename = "url")]
    pub url: String,
    #[serde(rename = "thumb_url", skip_serializing_if = "Option::is_none")]
    pub thumb_url: Option<String>,
    #[serde(rename = "is_video")]
    pub is_video: bool,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl Media {
    pub fn new(id: i32, uuid: uuid::Uuid, name: String, mime_type: String, r#type: Type, url: String, is_video: bool, created_at: String) -> Media {
        Media {
            id,
            uuid,
            name,
            mime_type,
            r#type,
            url,
            thumb_url: None,
            is_video,
            created_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "image")]
    Image,
    #[serde(rename = "video")]
    Video,
    #[serde(rename = "gif")]
    Gif,
}

impl Default for Type {
    fn default() -> Type {
        Self::Image
    }
}

