/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostVersion {
    /// Use `0` for the original/default version.
    #[serde(rename = "account_id")]
    pub account_id: i32,
    /// Must be `true` for the first version.
    #[serde(rename = "is_original")]
    pub is_original: bool,
    #[serde(rename = "content")]
    pub content: Vec<models::PostContent>,
    /// Platform-specific publishing options.
    #[serde(rename = "options", skip_serializing_if = "Option::is_none")]
    pub options: Option<serde_json::Value>,
}

impl PostVersion {
    pub fn new(account_id: i32, is_original: bool, content: Vec<models::PostContent>) -> PostVersion {
        PostVersion {
            account_id,
            is_original,
            content,
            options: None,
        }
    }
}

