/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostInput {
    /// At least one version with `is_original: true` is required.
    #[serde(rename = "versions")]
    pub versions: Vec<models::PostVersion>,
    /// Account IDs to publish to.
    #[serde(rename = "accounts", skip_serializing_if = "Option::is_none")]
    pub accounts: Option<Vec<i32>>,
    /// Tag IDs to attach.
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<i32>>,
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    #[serde(rename = "time", skip_serializing_if = "Option::is_none")]
    pub time: Option<String>,
    #[serde(rename = "timezone", skip_serializing_if = "Option::is_none")]
    pub timezone: Option<String>,
    /// Schedule the post for the given date/time.
    #[serde(rename = "schedule", skip_serializing_if = "Option::is_none")]
    pub schedule: Option<bool>,
    /// Publish immediately.
    #[serde(rename = "schedule_now", skip_serializing_if = "Option::is_none")]
    pub schedule_now: Option<bool>,
    /// Add to the smart publishing queue.
    #[serde(rename = "queue", skip_serializing_if = "Option::is_none")]
    pub queue: Option<bool>,
}

impl PostInput {
    pub fn new(versions: Vec<models::PostVersion>) -> PostInput {
        PostInput {
            versions,
            accounts: None,
            tags: None,
            date: None,
            time: None,
            timezone: None,
            schedule: None,
            schedule_now: None,
            queue: None,
        }
    }
}

