/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Post {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
    #[serde(rename = "status")]
    pub status: models::PostStatus,
    #[serde(rename = "accounts")]
    pub accounts: Vec<models::Account>,
    #[serde(rename = "versions")]
    pub versions: Vec<models::PostVersion>,
    #[serde(rename = "tags")]
    pub tags: Vec<models::Tag>,
    #[serde(rename = "scheduled_at", skip_serializing_if = "Option::is_none")]
    pub scheduled_at: Option<String>,
    #[serde(rename = "published_at", skip_serializing_if = "Option::is_none")]
    pub published_at: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: String,
    #[serde(rename = "trashed")]
    pub trashed: bool,
}

impl Post {
    pub fn new(id: i32, uuid: uuid::Uuid, status: models::PostStatus, accounts: Vec<models::Account>, versions: Vec<models::PostVersion>, tags: Vec<models::Tag>, created_at: String, trashed: bool) -> Post {
        Post {
            id,
            uuid,
            status,
            accounts,
            versions,
            tags,
            scheduled_at: None,
            published_at: None,
            created_at,
            trashed,
        }
    }
}

