/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReceiptUpdateInput {
    #[serde(rename = "transaction_id")]
    pub transaction_id: String,
    #[serde(rename = "invoice_number")]
    pub invoice_number: String,
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "tax", skip_serializing_if = "Option::is_none")]
    pub tax: Option<f64>,
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "receipt_url", skip_serializing_if = "Option::is_none")]
    pub receipt_url: Option<String>,
    #[serde(rename = "paid_at")]
    pub paid_at: String,
}

impl ReceiptUpdateInput {
    pub fn new(transaction_id: String, invoice_number: String, amount: f64, currency: String, paid_at: String) -> ReceiptUpdateInput {
        ReceiptUpdateInput {
            transaction_id,
            invoice_number,
            amount,
            tax: None,
            currency,
            description: None,
            receipt_url: None,
            paid_at,
        }
    }
}

