/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 8+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Subscription {
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "platform_subscription_id", skip_serializing_if = "Option::is_none")]
    pub platform_subscription_id: Option<String>,
    #[serde(rename = "platform_plan_id", skip_serializing_if = "Option::is_none")]
    pub platform_plan_id: Option<String>,
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<models::SubscriptionStatus>,
    #[serde(rename = "recurring", skip_serializing_if = "Option::is_none")]
    pub recurring: Option<bool>,
    #[serde(rename = "trial_ends_at", skip_serializing_if = "Option::is_none")]
    pub trial_ends_at: Option<String>,
    #[serde(rename = "paused_from", skip_serializing_if = "Option::is_none")]
    pub paused_from: Option<String>,
    #[serde(rename = "ends_at", skip_serializing_if = "Option::is_none")]
    pub ends_at: Option<String>,
}

impl Subscription {
    pub fn new() -> Subscription {
        Subscription {
            name: None,
            platform_subscription_id: None,
            platform_plan_id: None,
            status: None,
            recurring: None,
            trial_ends_at: None,
            paused_from: None,
            ends_at: None,
        }
    }
}

