/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubscriptionInput {
    #[serde(rename = "platform_subscription_id")]
    pub platform_subscription_id: String,
    #[serde(rename = "platform_plan_id")]
    pub platform_plan_id: String,
    #[serde(rename = "status")]
    pub status: models::SubscriptionStatus,
    /// Required when status is `trialing`.
    #[serde(rename = "trial_ends_at", skip_serializing_if = "Option::is_none")]
    pub trial_ends_at: Option<String>,
}

impl SubscriptionInput {
    pub fn new(platform_subscription_id: String, platform_plan_id: String, status: models::SubscriptionStatus) -> SubscriptionInput {
        SubscriptionInput {
            platform_subscription_id,
            platform_plan_id,
            status,
            trial_ends_at: None,
        }
    }
}

