/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "email")]
    pub email: String,
    #[serde(rename = "is_admin")]
    pub is_admin: bool,
    #[serde(rename = "email_verified_at", skip_serializing_if = "Option::is_none")]
    pub email_verified_at: Option<String>,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl User {
    pub fn new(id: i32, name: String, email: String, is_admin: bool, created_at: String) -> User {
        User {
            id,
            name,
            email,
            is_admin,
            email_verified_at: None,
            created_at,
        }
    }
}

