/*
 * PostBoost API
 *
 * The PostBoost REST API lets you publish, schedule, and analyze social media posts across 12+ platforms from a single integration. No OAuth apps to maintain — PostBoost handles platform authorization for you.  ## Base URL All workspace-scoped endpoints are prefixed with `/{workspaceUuid}`. Panel/admin endpoints are prefixed with `/panel`.  ## Authentication All requests require a Bearer token in the `Authorization` header. Generate tokens in your PostBoost dashboard under **Settings → Access Tokens**.  ``` Authorization: Bearer YOUR_API_TOKEN ``` 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: hi@postboost.co
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Workspace {
    #[serde(rename = "uuid")]
    pub uuid: uuid::Uuid,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "hex_color")]
    pub hex_color: String,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<Box<models::User>>,
    #[serde(rename = "access_status")]
    pub access_status: AccessStatus,
    #[serde(rename = "created_at")]
    pub created_at: String,
}

impl Workspace {
    pub fn new(uuid: uuid::Uuid, name: String, hex_color: String, access_status: AccessStatus, created_at: String) -> Workspace {
        Workspace {
            uuid,
            name,
            hex_color,
            owner: None,
            access_status,
            created_at,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccessStatus {
    #[serde(rename = "subscription")]
    Subscription,
    #[serde(rename = "unlimited")]
    Unlimited,
    #[serde(rename = "locked")]
    Locked,
}

impl Default for AccessStatus {
    fn default() -> AccessStatus {
        Self::Subscription
    }
}

